[package]
name = "arcui-platform-win32"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
arcui-core = { path = "../arcui-core" }

[dependencies.windows]
version = "0.62.2"
features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
]
